nodeLinker: node-modules
# This will make yarn pin exact versions of deps when installing new packages
defaultSemverRangePrefix: ""
# Always show build output (including pod install messages)
enableInlineBuilds: true
# Ensure scripts always run
enableScripts: true
