import { isProd } from "helpers/isEnv";
import Config from "react-native-config";

/**
 * Get environment-specific configuration based on bundle ID
 */
const getEnvConfig = () => ({
  AMPLITUDE_API_KEY: Config.AMPLITUDE_API_KEY,
  AMPLITUDE_EXPERIMENT_DEPLOYMENT_KEY:
    Config.AMPLITUDE_EXPERIMENT_DEPLOYMENT_KEY,

  SENTRY_DSN: Config.SENTRY_DSN,

  FREIGHTER_BACKEND_URL: Config.FREIGHTER_BACKEND_URL,
  FREIGHTER_BACKEND_V2_URL: Config.FREIGHTER_BACKEND_V2_URL,

  WALLET_KIT_PROJECT_ID: Config.WALLET_KIT_PROJECT_ID,
  WALLET_KIT_MT_URL: Config.WALLET_KIT_MT_URL,
  WALLET_KIT_MT_ICON: Config.WALLET_KIT_MT_ICON,

  // Get wallet kit metadata based on bundle ID
  WALLET_KIT_MT_NAME: isProd
    ? Config.WALLET_KIT_MT_NAME_PROD
    : Config.WALLET_KIT_MT_NAME_DEV,
  WALLET_KIT_MT_DESCRIPTION: isProd
    ? Config.WALLET_KIT_MT_DESCRIPTION_PROD
    : Config.WALLET_KIT_MT_DESCRIPTION_DEV,
  WALLET_KIT_MT_REDIRECT_NATIVE: isProd
    ? Config.WALLET_KIT_MT_REDIRECT_NATIVE_PROD
    : Config.WALLET_KIT_MT_REDIRECT_NATIVE_DEV,

  ANDROID_DEBUG_KEYSTORE_PASSWORD: Config.ANDROID_DEBUG_KEYSTORE_PASSWORD,
  ANDROID_DEBUG_KEYSTORE_ALIAS: Config.ANDROID_DEBUG_KEYSTORE_ALIAS,
  ANDROID_DEV_KEYSTORE_PASSWORD: Config.ANDROID_DEV_KEYSTORE_PASSWORD,
  ANDROID_DEV_KEYSTORE_ALIAS: Config.ANDROID_DEV_KEYSTORE_ALIAS,
  ANDROID_PROD_KEYSTORE_PASSWORD: Config.ANDROID_PROD_KEYSTORE_PASSWORD,
  ANDROID_PROD_KEYSTORE_ALIAS: Config.ANDROID_PROD_KEYSTORE_ALIAS,
});

export const EnvConfig = getEnvConfig();

export const {
  AMPLITUDE_API_KEY,
  AMPLITUDE_EXPERIMENT_DEPLOYMENT_KEY,

  FREIGHTER_BACKEND_URL,
  FREIGHTER_BACKEND_V2_URL,

  WALLET_KIT_PROJECT_ID,
  WALLET_KIT_MT_NAME,
  WALLET_KIT_MT_DESCRIPTION,
  WALLET_KIT_MT_URL,
  WALLET_KIT_MT_ICON,
  WALLET_KIT_MT_REDIRECT_NATIVE,

  SENTRY_DSN,

  ANDROID_DEBUG_KEYSTORE_PASSWORD,
  ANDROID_DEBUG_KEYSTORE_ALIAS,
  ANDROID_DEV_KEYSTORE_PASSWORD,
  ANDROID_DEV_KEYSTORE_ALIAS,
  ANDROID_PROD_KEYSTORE_PASSWORD,
  ANDROID_PROD_KEYSTORE_ALIAS,
} = EnvConfig;
